# Required CONDA packages (compare README).
# All other (pip) packages are installed with pip
# `pip install .`  or
# `pip install .[testing]`  or
# `pip install .[docs]`  or
# `pip install repurpose`
name: repurpose
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - netCDF4
  - pyproj
