# Required conda packages (compare README).
# All other (pip) packages are installed with pip
# `pip install .`  or
# `pip install .[testing]`  or
# `pip install .[docs]`  or
name: repurpose
channels:
  - defaults
  - conda-forge
dependencies:
  - xarray
  - netCDF4
  - pyproj
