#this file is not used at the moment
name: repurpose-docs
channels:
  - conda-forge
dependencies:
- netcdf4
- numpy
- scipy
- pandas
- matplotlib
- pyresample
- python=3.6
- pip:
    - pynetcf
    - pytesmo
